### PR TITLE
util: Allow user to set qmake binary name over full path

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by TheAssassin** [comment]
Hm... is it asked too much to do the `which` outside of the plugin? `env QMAKE="$(which qmake)" ...`

That said, I don't mind the change per se. I just need to think about potential security implications...

**Comment by TheAssassin** [comment]
Please provide a use case in which this feature _really_ makes sense.

**Comment by patrickelectric** [comment]
> Please provide a use case in which this feature _really_ makes sense.

In a GitHub action, or any system I just want to say qmake6 over specifying the path manually or using which in my command line (that's already not small).

I don't see a problem with the change, the current use case does not change, just improves making it easy to use, my first try was to use qmake6, and it was necessary to look at the code to see that it needs a full path.

**Comment by TheAssassin** [comment]
Fair enough. Please do me a favor and check whether `which(...)` works with absolute paths. I might not get around to do it myself anytime soon.

**Comment by patrickelectric** [comment]
> Fair enough. Please do me a favor and check whether `which(...)` works with absolute paths. I might not get around to do it myself anytime soon.

Yep, I did test before sending the PR.

**Comment by TheAssassin** [comment]
Awesome! Would you mind to fix the CI by pushing a commit similar to https://github.com/linuxdeploy/linuxdeploy/commit/91631c1b2f0cb0f5de9f4af2e4ca4c9dc91dc09f?

**Review by TheAssassin — APPROVED** [review]

**Comment by patrickelectric** [comment]
> Awesome! Would you mind to fix the CI by pushing a commit similar to [linuxdeploy/linuxdeploy@91631c1](https://github.com/linuxdeploy/linuxdeploy/commit/91631c1b2f0cb0f5de9f4af2e4ca4c9dc91dc09f)?

Check #137

**Comment by patrickelectric** [comment]
FYI: It's working with Qt6 without problems

**Comment by patrickelectric** [comment]
I'm moving [QHot](https://github.com/patrickelectric/qhot) to Qt6 and got an AppImage running.

**Comment by TheAssassin** [comment]
That's great to hear! I'm about to publish a little Qt 6 app, too.

**Comment by TheAssassin** [comment]
Thanks!

**Comment by bjorn** [comment]
> Yep, I did test before sending the PR.

Hmm, looking at the source code, absolute paths would always make it return an empty string:

https://github.com/linuxdeploy/linuxdeploy/blob/91631c1b2f0cb0f5de9f4af2e4ca4c9dc91dc09f/include/linuxdeploy/util/misc.h#L105-L130

**Comment by patrickelectric** [comment]
> > Yep, I did test before sending the PR.
> 
> Hmm, looking at the source code, absolute paths would always make it return an empty path:
> 
> https://github.com/linuxdeploy/linuxdeploy/blob/91631c1b2f0cb0f5de9f4af2e4ca4c9dc91dc09f/include/linuxdeploy/util/misc.h#L105-L130

I thought that the `which` of `linuxdeploy` was based over the `which` cli tool, that I did test.

There is a PR for linuxdeploy that updates the which function to have the same functionality.

https://github.com/linuxdeploy/linuxdeploy/pull/243

**Comment by patrickelectric** [comment]
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/138 should fix the issue

**Pull request merged**
