### PR TITLE
Copy v8_context_snapshot.bin to resources when deploying Qt WebEngine.

### PR DESCRIPTION
**Pull request by camilasan**
This file was added in Qt6.

See https://doc.qt.io/qt-6/qtwebengine-deploying.html

### CODE REVIEW

**Comment by TheAssassin** [comment]
Given the opportunistic approach (i.e., we copy if the file if it exists and skip it otherwise), this shouldn't break compatibility with Qt 5. Therefore, I'm willing to merge it. Let's see what the CI has to say.

**Comment by TheAssassin** [comment]
Thanks!

**Comment by mgallien** [comment]
@TheAssassin I was planning to use the fix made by @camilasan 
is there something I can help with to get it published to continuous ?

**Comment by TheAssassin** [comment]
I'm preparing a PR at the moment.

**Pull request merged**
