### PR TITLE
Fix crash with qt6 and multimedia plugin

### PR DESCRIPTION
**Pull request by smarttowel**
Qt6 doesn't contain plugins/mediaservice dir

### CODE REVIEW

**Comment by TheAssassin** [comment]
Could you provide a link to a build log, please? Or at least a log excerpt.

**Comment by vadi2** [comment]
Qt6 does ship multimedia, and it would be important to still support it: https://doc.qt.io/qt-6/qtmultimedia-index.html

**Comment by TheAssassin** [comment]
This is what I thought as well. I'm curious to see how the plugin "crashes". I am pretty sure we just have to improve the deployer.

**Comment by TheAssassin** [comment]
Please add either the complete log or at least the (possibly censored) Qt plugin log.

**Comment by smarttowel** [comment]
[log.txt](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/files/8941547/log.txt)

**Review by bjorn — APPROVED** [review]
According to the post linked by @smarttowel, QtMultimedia no longer has any plugins:

> With Qt6, we have chosen to significantly simplify this and removed the plugin infrastructure. The backend is now chosen at compile time and compiled into the shared library for Qt Multimedia.

So, skipping the `MultimediaPluginsDeployer` entirely seems like a valid fix to me.

**Comment by TheAssassin** [comment]
Thanks!

**Pull request merged**
