### PR TITLE
Enable webengine deployment for Qt6

### PR DESCRIPTION
**Pull request by danryu**
This PR enables the webengine deployer in linuxdeploy-plugin-qt for Qt6.

NOTE: 6.0.x and 6.1.x series are not supported. Current LTS release 6.2.4 (and later) bring many improvements with little or no compatibility issues.

Tested as working with Qt 6.2.4 and Qt 6.3.0 here: https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/112

### CODE REVIEW

**Comment by bjorn** [comment]
Will simply moving these modules to the Qt6 list break the plugin when used with Qt 6 releases that did not have these modules yet? Or we don't care for Qt 6.0 and 6.1 support anymore?

**Comment by danryu** [comment]
@bjorn My 2 cents: I strongly recommend targeting only the LTS release in the 6.x series (ie 6.2.4) and later. 6.3.0 is also generally available and a transparent upgrade in my experience. I don't expect there to be any focus on 6.0.x or 6.1.x from qt.io themselves, so I think it is an unnecessary burden for this project, considering the overall overhead of the 5->6 transition.

**Comment by bjorn** [comment]
Right, I spent some time getting this plugin to work for 6.0 and 6.1 in #101, because there was some issue with switching my builds to 6.2. These have since been resolved though, so at this point I wouldn't mind to drop support for these Qt releases either.

**Comment by TheAssassin** [comment]
I'd just ignore Qt < 6.2 for now, honestly. We can consider these out of date. >= 6.2 bring plenty improvements, and I don't see any compatibility issues that would prevent anyone from upgrading.

We should perhaps add a note in the README. @danryu could you please add this to your PR?

**Comment by danryu** [comment]
@TheAssassin Added note to PR as requested.

One thought: it's highly likely IMO that most (if not all) of the remaining modules in Qt6Modules are probably good to integrate at this stage in 6.x maturity.

**Comment by TheAssassin** [comment]
I guess so, but I'm not sure all of them have been reimplemented in Qt 6.2 already. Would be very willing to merge such a change, so if you have a few minutes, please feel free to update this PR (or send a new one), otherwise I'll merge this tonight. Thanks for your contribution!

**Comment by TheAssassin** [comment]
Merging for now. Thanks!

**Comment by danryu** [comment]
@TheAssassin I'll do a separate PR for the other modules

**Pull request merged**
